###
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "fer@gmail.com",
    "password": "1234"
}

###
POST http://localhost:3000/api/usuarios/registro
Content-Type: application/json

{
    "nombre": "Fernando",
    "primer_apellido": "Reviriego",
    "segundo_apellido": "Pina",
    "email": "fer2@gmail.com",
    "fecha_nacimiento": "01/01/1986",
    "nombre_usuario": "fer24",
    "password": "12345"
}
